CREATE TABLE IF NOT EXISTS PUBLIC.host_info
(
	id SERIAL PRIMARY KEY NOT NULL,
	hostname VARCHAR (255) NOT NULL UNIQUE,
	cpu_number INTEGER NOT NULL,
	cpu_architecture VARCHAR (50) NOT NULL,
	cpu_model VARCHAR (255) NOT NULL,
	cpu_mhz FLOAT NOT NULL,
	L2_cache VARCHAR NOT NULL,
	total_mem INTEGER NOT NULL,
	"timestamp" TIMESTAMP NOT NULL
);

CREATE TABLE IF NOT EXISTS PUBLIC.host_usage
(
	"timestamp" TIMESTAMP NOT NULL,
	host_id SERIAL NOT NULL REFERENCES host_info(id),
	memory_free INTEGER NOT NULL,
	cpu_idle INTEGER NOT NULL,
	cpu_kernel INTEGER NOT NULL,
	disk_io INTEGER NOT NULL,
	disk_available INTEGER NOT NULL

);
